### ISSUE TITLE
Things to fix...

### ISSUE THREAD

**Issue by arguiot** [pr1mer-tech/lunar-icons#1]
In this issue, I will simply list all the things you should change/add/improve to make this project better.

This is my list (I might forget a lot of stuff):
- Broken links: stop making menus on the website if you don't have the pages 😊 (it's annoying)
- Stuff icons: you don't have icons for objects, services, etc...
- Code preview: it will be good if when you click on an icon (on the website) that there is a pop-up that shows the code (easy to do, but helpful for lazy guys).
- Roadmap: If GitHub introduced the "Projects" section, it's to use it 😂.
- Better `README.md`
- The image in the docs

That's all (for the moment), I really like this project, the icons are great (except maybe for the Wi-Fi one). I hope more icons will come soon 😊.

**Comment by lucasgruwez** [comment]
Soon...

![Sneak preview](https://lucasgruwez.github.io/lunar-icons/img/sneakPrev.png)

**Comment by arguiot** [comment]
Great to see that you didn’t abandon the project 😊.
