### ISSUE TITLE
Social logos

### ISSUE THREAD

**Issue by arguiot** [pr1mer-tech/lunar-icons#2]
Hello 👋,  
As you designed lunar icons for the web, it would be nice to have social logos, such as:
- Twitter
- Facebook
- GitHub
- Codepen
- Instagram
- Medium
- Google (and Google +)
- Discord
- YouTube
- Unsplash

It should be easy for you to implement that because you can just copy paste the SVGs on the company's website.

**Comment by lucasgruwez** [comment]
These Icons should be released by v1.1.0

They will however not be a copy-paste from the website, as I would like all icons to have a unified style.

Also, google+? Seriously?

**Comment by arguiot** [comment]
Ok, I understand, but you can still copy the path and use a stroke to do your unified style

**Comment by lucasgruwez** [comment]
After testing a bit, I have come to the conclusion that it is better to leave the brand icons as is. They will be included in 1.1.0, but will be in a separate from the normal icons on the website.

**Comment by arguiot** [comment]
Ok, I think your decision is reasonable

**Comment by lucasgruwez** [comment]
Here is a library with tons of brand icons. I think it's better to just use that instead of create our own.

https://simpleicons.org

**Comment by arguiot** [comment]
Yeah, but my problem was that I don't want to increase load time. So you can add just the basic icons (github, facebook, twitter, YouTube and Discord)

**Comment by lucasgruwez** [comment]
I've been fiddling around a bit more, and am still unsure how I'm going to deal with the brand icons. This pull request will be closed, but, I'll reopen it later, when brand icons will be added.

**Comment by lucasgruwez** [comment]
Brand icons will have the lunar icons style. Might add the original logos in a later release.
