### ISSUE TITLE
Web Components and Node entry point

### ISSUE THREAD

**Issue by arguiot** [pr1mer-tech/lunar-icons#5]
I know that custom elements are fantastic and everyone should use them.

But it's stupid to change the node entry point to that because many browsers still don't support custom elements.

https://caniuse.com/#feat=custom-elementsv1

I think you should put the node entry point back where it was, and still include the `replace` method.

So you'll have 2 two files: `[...].js` and `[...].min.js`. In both of these files, custom elements should be supported, but the `replace` method would still be there.

I think it would be a better way of using custom components

**Comment by lucasgruwez** [comment]
Ok working on it

**Comment by lucasgruwez** [comment]
Done!
